theme: jekyll-theme-cayman
title: Ystia Suite
description: Develop and deploy applications over hybrid infrastructures (IaaS, HPC schedulers, CaaS).
github:
  yorc:
    repository_url: https://github.com/ystia/yorc
  forge:
    repository_url: https://github.com/ystia/forge
  a4c_plugin:
    repository_url: https://github.com/ystia/yorc-a4c-plugin

